### PR TITLE
Add 'executable' product to support latest Mint version

### LINKED ISSUE #1: Following README results in "Executable product not found"
I've used your project before without issue, but I'm on a new machine and am running into this error when I try and run it. I briefly looked into Mint's code and see the error is originating there. I'm curious if it's me or if a new version of Mint changed things or...

### PR DESCRIPTION
**Pull request by lrossi**
Fixes #1.

### CODE REVIEW

**Comment by zweigraf** [comment]
Thank you!

**Comment by factotvm** [comment]
@lrossi Were you able to get it to work? I'm receiving the following:

```sh
$ mint run zweigraf/FakeBundle "fakebundle --input ./Resources --output ./Resources.swift"
🌱  Finding latest version of FakeBundle
🌱  Resolved latest version of FakeBundle to master
🌱  Cloning https://github.com/zweigraf/FakeBundle.git master...
🌱  Building FakeBundle Package with SPM...
🌱  Installing FakeBundle...
🌱  Installed FakeBundle master
Couldn't find executable "fakebundle --input ./Resources --output ./Resources.swift"
```

**Comment by zweigraf** [comment]
I can’t test it right now, but going from https://github.com/yonaskolb/Mint/blob/master/README.md and checking their Examples section, I think you should leave off the quotation marks. This might have changed with Mint.

So try running

    mint run zweigraf/FakeBundle fakebundle --input ...

**Comment by factotvm** [comment]
You're right. I've submitted a pull request to update the README. Thanks @zweigraf!

**Comment by zweigraf** [comment]
Thanks @factotvm! Readme now fixed via #4

**Comment by lrossi** [comment]
You're right, I forgot to update the README! Good catch and thanks for fixing it @factotvm!

**Pull request merged**
